<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Database\Eloquent\Factories\Factory;
use Tests\TestCase;

class AuthUserTest extends TestCase
{

    use RefreshDatabase, WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAuthUserRedirectsHome()
    {
        $this->artisan("db:seed");
        $user = User::factory()->create();
        $this->actingAs($user);

        $response = $this->get('/home');

        $response->assertStatus(200);
    }

    public function testNotAuthUserRedirectsLogin()
    {
        $response = $this->get('/home');

        $response->assertRedirect('/login');
    }

    public function testNotAuthUserRegister(){
        $response = $this->get('/register');

        $response->assertStatus(200);
    }
}
