<?php

namespace Tests\Feature;

use App\Models\Group;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Session;
use Tests\TestCase;

class GroupTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    private $user;
    private $groupData;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Session::start();
        $this->user = User::factory()->create(['role_id' => 2]);
        $this->actingAs($this->user);
        $this->groupData = [
            '_token' => csrf_token(),
            'title' => 'Title',
            'group_description' => 'Group description',
            'category_id' => 1
        ];
    }

    public function testAllGroupsRightPage(){
        $response = $this->get('groups');
        $response->assertOk();
        $response->assertViewHas('isAll', true);
        $response->assertViewIs('group.groups');
    }

    public function testUserGroups(){
        $response = $this->get("groups/{$this->user->id}");

        $response->assertOk();
        $this->assertCount(0, $this->user->groups);
        $response->assertViewHas('isAll', false);
    }

    public function testValidDataGroup(){
        $response = $this->post('groups', $this->groupData);

        $response->assertValid();
        $response->assertSessionHas('group_success');
    }

    public function testInvalidDataGroup(){
        $response = $this->post('groups', ['group_description' => 'description', '_token' => csrf_token()]);

        $response->assertInvalid();
    }

    public function testDeleteGroup(){
        $this->get('/home');
        $response = $this->get('groups');
        $response->assertViewHas('isAdmin', true);

        $this->post(route('groups.store'), $this->groupData);
        $group = Group::all()->last();
        $count = count(Group::all());

        $response = $this->delete(route('groups.destroy', $group->id), ['_token' => csrf_token()]);

        unset($this->groupData['_token']);
        $this->assertDeleted('groups', $this->groupData);
        $this->assertCount($count-1, Group::all());
        $response->assertSessionHas('group_success');
    }
}
