<?php

namespace Tests\Feature;

use App\Models\Group;
use App\Models\GroupUser;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Tests\TestCase;

class GroupUserTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Session::start();
        $this->user = User::factory()->create(['role_id' => 2]);
        $this->actingAs($this->user);
    }

    public function testSubscribeGroup(){
        $this->get('goals');
        $response = $this->post(route('subscribe.edit', 1), ['_token' => csrf_token()]);
        $userGroups = $this->user->groups->all();
        $response->assertRedirect('/groups?page=1');
        $this->assertCount(1, $userGroups);
    }

    public function testUnsubscribeGroup(){
        $this->get('goals');
        $group = Group::find(1)->toArray();

        $this->post(route('subscribe.edit', $group['id']), ['_token' => csrf_token()]);
        $this->delete(route('subscribe.destroy', $group['id']), ['_token' => csrf_token()]);

        $this->assertDeleted('group_user', ['user_id' => $this->user->id]);
    }
}
