<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class IsAdminTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    private $user;
    private $response;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create([
            'role_id' => 2
        ]);
        $this->actingAs($this->user);
        $this->response = $this->get('/home');
    }

    public function testIsCanCreateGroups(){
        $this->response = $this->get('/groups');
        $this->response->assertViewHas('isAdmin', true);

        $this->response = $this->get('groups/create');
        $this->response->assertOk();
    }

    public function testIsAdmin(){
        $this->response->assertViewHas('isAdmin', true);
        $this->response->assertSessionHas('isAdmin');
    }
}
