<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LocaleTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->actingAs($this->user);
    }

    public function testSetLocale(){
        $response = $this->get(route('changeLocale', 'UA'));
        $response->assertRedirect();
        $response->assertSessionHas('locale');
        $response->assertSessionHasNoErrors();
    }

    public function testTranslation(){
        $this->get(route('changeLocale', 'UA'));
        $response = $this->get('/home');

        $response->assertSeeText(['МЕНЮ', 'Профіль', 'Список цілей', 'Мої групи', 'Мої друзі']);
        $response->assertDontSeeText(['MENU', 'Home', 'Goals', 'My groups', 'My friends']);
    }
}
