<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Session;
use Tests\TestCase;

class ValidationUserInfoTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Session::start();
    }

    public function testUserInfoValidation(){
        $user = User::factory()->create();
        $this->actingAs($user);

        $response = $this->post('/user/info', [
            '_token' => csrf_token(),
            'full_name' => 'Daria Levkun',
            'email' => 'levkun.dasha@gmail.com',
            'nickname' => 'hangsang',
        ]);

        $response->assertValid();
        $response->assertRedirect('/home');
    }

    public function testUserDescriptionValidation(){
        $user = User::factory()->create();
        $this->actingAs($user);

        $response = $this->post('/user/description', [
            'description' => 'Hello world',
            '_token' => csrf_token()
        ]);

        $response->assertValid();
    }

    public function testUserInvalidInfoValidation(){
        $user = User::factory()->create();
        $this->actingAs($user);

        $response = $this->post('/user/info', [
            'email' => 'levkun.dasha',
            '_token' => csrf_token()
        ]);

        $response->assertInvalid();
    }
}
